### ISSUE TITLE
Agregar un loading 

### ISSUE THREAD

**Issue by f0go** [yohannaje/BurgerMap-iOS#18]

**Comment by nameghino** [comment]
Un loading a qué?

**Comment by f0go** [comment]
Ni puta idea jajajaja Me parece que Julito me había dicho que cargue este issue

**Comment by nameghino** [comment]
Acá Julio dice que fue Luis y no que fue el

**Comment by f0go** [comment]
Asignale el issue a Luis ᕕ( ՞ ᗜ ՞ )ᕗ
