### ISSUE TITLE
App description

### ISSUE THREAD

**Issue by nameghino** [yohannaje/BurgerMap-iOS#24]
Texto, inglés, máximo 4K caracteres

**Comment by yohannaje** [comment]
BurgerMap is an application that allows you to find burger joints near you.
just allow the app to display your location and you'll se the nearer joints on the map. 
After you find a joint you'd like to attend, you can see its description, rating and distance, get directions and also its website or phone number.

Get BurgerMap and dont miss its updates, as we're coming up with more exciting features!
