### ISSUE TITLE
menu fixes

### ISSUE THREAD

**Issue by yohannaje** [yohannaje/BurgerMap-iOS#4]
- [x] poner lineas intermedias (hex: #9B9B9B , weight: 0.5)
- [x] agregar iconos
- [x] cambiar el hover al naranja de la ui
- [x] agregar credit cards
- [x] agregar open now
- [x] agregar price range
- [x] cambiar el titulo de Add review a My Reviews.

![new-menu](https://cloud.githubusercontent.com/assets/829179/10865774/0129f30c-7ff6-11e5-9a4b-ebd40c1de38b.png)

**Comment by nameghino** [comment]
Hover? Qué es eso?

**Comment by nameghino** [comment]
Las celdas de shortcuts tienen que tener alguna altura en particular?

**Comment by nameghino** [comment]
Necesito íconos para "Open Now", "Takes Credit Cards" y el slider de precio

**Comment by nameghino** [comment]
BOOM, HEADSHOT
