### ISSUE TITLE
si tenes el menu abierto y probas abrir un punto en el mapa el menu no se cierra.

### ISSUE THREAD

**Issue by yohannaje** [yohannaje/BurgerMap-iOS#5]
![702222192_16717927913886946595](https://cloud.githubusercontent.com/assets/829179/10791531/905f06ca-7d67-11e5-9daa-839b1ccaeeee.jpg)

**Comment by nameghino** [comment]
No deberías poder entrar a un punto del mapa con el menú abierto

**Comment by nameghino** [comment]
fixed on c9f96

**Comment by nameghino** [comment]
Solo ocurría si tratabas de abrir un punto sin haber cerrado el menú
